default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: check-json
    -   id: check-xml
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
